### ISSUE TITLE
What is the plan for how to install this?

### ISSUE THREAD

**Issue by samhstn** [dwyl/tachyons-bootstrap#2]
Will it be a hex module?

**Comment by samhstn** [comment]
From #1 I see that it is not actually a library to be installed closing

**Comment by nelsonic** [comment]
@shouston3 if people *request* it, we *could* make it a module. But really, the idea was to have a set of component examples people can re-use.
That could take the form of code snippets or a module, but we should remind ourselves that one of the reasons Bootstrap is "bloated" is because it includes all things... (very few people bother to customise their bundle) ...
So we have to think it through before diving in. 😉
